Implement hubs feature on the backend
osdc/hermes pull request #15
Opened 2017-01-15 14:07 UTC by ryzokuken

2017-01-15 14:19 UTC, yashmehrotra requested changes

2017-01-15 14:19 UTC, yashmehrotra commented on api/hub_api.go
> +	// TODO: Write Serializers
@ryzokuken Please write the serializers :stuck_out_tongue:

2017-01-15 14:19 UTC, yashmehrotra commented on api/hub_api.go
> +func ShowHub(c echo.Context) error {
func GetHub

2017-01-15 14:19 UTC, yashmehrotra commented on server.go
> +	e.GET("/api/hub/show", api.ShowHub)
/api/hub/:slug

2017-01-15 14:19 UTC, yashmehrotra commented on api/hub_api.go
> +	slug := payload["slug"]
slug := c.Param("slug")

2017-01-15 14:19 UTC, yashmehrotra commented on api/hub_api.go
> +	slug := payload["slug"]
If no slug, return all hubs

2017-01-15 14:20 UTC, ryzokuken commented on server.go
> +	e.GET("/api/hub/show", api.ShowHub)
we'd make it that way on the frontend. Why use URL params on the backend?

2017-01-18 13:59 UTC, yashmehrotra requested changes
1. Serializers should be in their respective models.
2. Please Gofmt the files.
3. Name them like, user.Serialize() etc.

2017-01-18 13:59 UTC, yashmehrotra commented on server.go
> +	e.GET("/api/hub", api.ShowHubs)
GetAllHubs would be more consistent

2017-01-19 02:12 UTC, yashmehrotra requested changes

2017-01-19 02:12 UTC, yashmehrotra commented on models/hub.go
> +func (hub Hub) SerializeHub() map[string]interface{} {
Just `Serialize`

2017-01-19 02:12 UTC, yashmehrotra commented on models/user.go
> +func (user User) SerializeUser() map[string]interface{} {
Same, .... just `Serialize`

2017-01-20 01:47 UTC, merged