Added Initial backend plus API scripts.
osdc/hermes pull request #2
Opened 2016-12-19 18:59 UTC by wimpykid26

@yashmehrotra @526avijitgupta . Please review. Will write more API methods accordingly once I get a thumbs-up.

2016-12-19 19:09 UTC, ryzokuken reviewed
Please look into these if possible. Otherwise it looks great to me :) Awesome job @wimpykid26

2016-12-19 19:09 UTC, ryzokuken commented on server.go
> +  return c.String(http.StatusOK, "Inserted Hub Successfully")
Copy + Paste fail :P

2016-12-19 19:09 UTC, ryzokuken commented on db_setup.go
> +  db.AutoMigrate(&Users{}, &Hubs{}, &Announcements{}, &Events{}, &Roles{})
Shouldn't we also try seeding some dummy data at this point? It'll help with testing and also in the development environment.

2016-12-19 19:19 UTC, yashmehrotra commented
@wimpykid26 
1. Please run `gofmt` to format your code. 
2. Is the `sqlite` dependency required ?
3. You are missing `create_ts` and `update_ts` from the schema

2016-12-28 19:10 UTC, wimpykid26 commented
@yashmehrotra According to this, They have imported the `sqlite` dependency

2016-12-30 08:12 UTC, yashmehrotra requested changes

2016-12-30 08:12 UTC, yashmehrotra commented on db_setup.go
> +)
@wimpykid26 Change this to
```
import (
    "github.com/jinzhu/gorm"
    _ "github.com/jinzhu/gorm/dialects/postgres"
)
```

Since we are using PostgreSQL

2016-12-30 08:12 UTC, yashmehrotra commented on db_setup.go
> +	Event_Id    int    `gorm:"AUTO_INCREMENT"`
Just use `ID` everywhere.

2016-12-30 08:12 UTC, yashmehrotra commented on db_setup.go
> +	hub_id      int
It should be `HubID` and make similar changes to other foreign keys.

Also add foreign keys where ever necessary

2016-12-30 08:12 UTC, yashmehrotra commented on db_setup.go
> +	description string
`Description`, all the elements inside the `struct` should be capital.

2016-12-30 08:12 UTC, yashmehrotra commented on server.go
> +
Instead of rewriting the models everytime, create a `models.go` file and import them where ever required.

2016-12-30 08:12 UTC, yashmehrotra commented on server.go
> +}
All these functions should go to an `api.go` file and should be imported from there.

2016-12-30 19:44 UTC, wimpykid26 commented on db_setup.go
> +	Event_Id    int    `gorm:"AUTO_INCREMENT"`
As it turns out naming it as ID conflicts with the default column name 'id' already in the postgres db.

2016-12-30 19:46 UTC, wimpykid26 commented
Removing CreatedAt and UpdateAt as these columns are already present in the default gorm db structure alongwith 'deleted_at'.

2016-12-31 06:38 UTC, yashmehrotra requested changes

2016-12-31 06:38 UTC, yashmehrotra commented on api/api.go
> +	"github.com/wimpykid26/hermes/models"
This should be `github.com/osdc/hermes/models`, I'll give you access to make branch.

2016-12-31 06:38 UTC, yashmehrotra commented on server.go
> +	e.GET("/insert_user", api.Insert_user)
Lets divide api into, api/users.go, api/events.go, api/hubs.go, and similarly, keep the routes as, `/api/user/create` etc.

2017-01-01 11:23 UTC, 526avijitgupta commented
@wimpykid26 Please remove your fork. Create a branch out of the main repo - osdc/hermes and add your commits in that branch instead.

2017-01-01 11:33 UTC, yashmehrotra commented
@526avijitgupta @wimpykid26 Merging this now, going to make the remaining changes myself.

2017-01-01 11:33 UTC, merged